#!/bin/sh
#awk 'PROGRAM' FILENAME
#awk '{ print $1, $2 + 1 }' awkExp.output > awkExp.newoutput #just increase filed 2 by 1 for each line 	
#awk '{if ($1 == "the") print NR;}' $1 #print the line number which the field matches the
#awk '{ if($1 = "word2") print $1,  $2 + 2 > "echoExp.output" }' echoExp.output 
(tr ' ' '\n' | sort | uniq -c | awk '{ print $1, $2 }' ) << EOF



