#!/bin/sh
#Exercise 1.1:
#Write a command that finds the 10 most popular words in a file.

#Idea:
#The idea is to translate each alphabetic characters in a way which forming the characters(first argument) with -c option and compress identical newline character which is second argument with -s option.   


(tr -cs "[:alpha:]" '\n' | sort | uniq -c | sort -hr | head -n 10 ) < $1
#THe first sort command sorts the words alphabetically for counting words occurrencies of the same words and the second sort command sorts the occurrencies numerically with revesed order. Finally the head command list top 10 lines of words with occurencies by side. The line of commands are piped whci requies a file argument when bashing it.
